### ISSUE TITLE
how to run?

### ISSUE THREAD

**Issue by SeekPoint** [baiyyang/medical_ner_crfsuite#1]

**Comment by baiyyang** [comment]
just use the command
`python crf_unit.py`

**Comment by SeekPoint** [comment]
mldl@mldlUB1604:~/ub16_prj/medical_ner_crfsuite$ python crf_unit.py 
Traceback (most recent call last):
  File "crf_unit.py", line 34, in <module>
    train = readData('train.txt')
  File "crf_unit.py", line 25, in readData
    fr = codecs.open(filename, 'r', 'utf-8')
  File "/usr/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: 'train.txt'
mldl@mldlUB1604:~/ub16_prj/medical_ner_crfsuite$
