### ISSUE TITLE
如何从一句话中识别出实体

### ISSUE THREAD

**Issue by bananagg** [baiyyang/medical_ner_crfsuite#5]
你好，我用这种方法后，改了一下
teststr = '香港回归祖国，三峡水利工程截流长江'
testlist =[]
for i,ch in enumerate(teststr):
    d = []
    d.append(ch)
    testlist.append(d)
print(testlist)
tagger.tag(testlist)
为什么预测结果出来的全是O，我的训练集中标记为BMEO，是一个地址识别。

**Comment by baiyyang** [comment]
你好，你的testlist里面是以字为单位，并且只记录了字的信息，如果没有识别出地址的话，我认为可能有两个原因：
1. 训练集量少，crf模型效果一般。
2. CRF特征只有一个字信息，特征数量不够。

祝好！
