### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by adzhua** [baiyyang/medical_ner_crfsuite#6]
你好train.txt和test.txt中的数据是从data文件夹中的数据转换来的吗？

**Comment by baiyyang** [comment]
你好，
        train.txt和test.txt中的数据是从data文件夹中的数据转换来。通过reader.py文件。




| |
baiyyang
|
|
baiyyang@163.com
|


在2018年11月5日 13:41，adzhua<notifications@github.com> 写道：

你好train.txt和test.txt中的数据是从data文件夹中的数据转换来的吗？
